version: '3'

services:
#  bzdacs:
#    image: hardstylez72/bzdacs:latest
#    restart: always
#    ports:
#      - 8888:8080
#    environment:
#      BZDACS_LOGIN: admin
#      BZDACS_PASSWORD: admin
#      BZDACS_POSTGRES: host=postgres port=5432 user=postgres password=postgres dbname=default sslmode=disable
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 6667:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
#  jaeger:
#    image: "jaegertracing/all-in-one:1.14"
#    restart: always
#    ports:
#      - 5775:5775/udp
#      - 6831:6831/udp
#      - 6832:6832/udp
#      - 5778:5778
#      - 16686:16686
#      - 14268:14268
#      - 9411:9411
    network_mode: host