env: dev
host: http://localhost:4000
backend:
  port: :4000
database:
  postgres: host=localhost port=6667 user=postgres password=postgres dbname=postgres sslmode=disable

internal:
  login: hs
  password: 1234

  sessionExpirationInSeconds: 600

  system: BZDACS
  namespace: internal
  adminGroupName: admin
  adminGroupDescription: internal admin system group, all grants

  hasGuest: true
  guestGroupName: guest
  guestGroupDescription: internal guest system group, grunts for views

